config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'kitchen_sink' => 'static_pages#kitchen_sink'
  get 'gallery' => 'art_pieces#index'

  resources :artists
  resources :art_pieces

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/art_piece.rb
class ArtPiece < ActiveRecord::Base

  belongs_to :artist

  has_attached_file :image, default_url: "/images/:style/missing.png",
    styles: { medium: "300x300>" }

  validates_attachment :image, presence: true, content_type: { content_type: /\Aimage\/.*\Z/ }

  scope :highlighted, -> { where(highlighted: true) }
  scope :by_artist, -> (name) { includes(:artist).where(artists: { name: name })}

  def author
    artist
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :art_pieces, inverse_of: :artist

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/art_pieces_controller.rb
class ArtPiecesController < ApplicationController
  expose_decorated(:art_piece)
  expose_decorated(:art_pieces)

  def index
    return if params[:artist].blank?
    self.art_pieces = ArtPiece.by_artist(params[:artist])
  end

  def show

  end

  private

  def filter_params
    params.require(:filter).permit(:artist)
  end

  def art_piece_params
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  expose_decorated(:artists)
  expose_decorated(:artist, attributes: :artist_params)

  def index
  end

  def show
    render :show, layout: 'artist'
  end

  def new
  end

  def create
    if artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def artist_params
    params.require(:artist).permit(:first_name, :last_name, :description)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/art_pieces_helper.rb
module ArtPiecesHelper
  def gallery_filtered_by_artist_path(artist)
    gallery_path + "?artist=" + artist.name.gsub(/\s/, '+')
  end

  def price_in_pounds(price)
    number_to_currency(price, unit: '£')
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/art_pieces/index.slim
.art-pieces-wrapper
  - art_pieces.each do |art_piece|
    .art-piece-item
      = link_to art_piece_path(art_piece), class: 'art-piece-item__art-piece-link'
        .art-piece-item__image-wrapper
          .art-piece-item__image
            img[class=art_piece.wide_or_tall?.to_s
              src=art_piece.image.url]
        .art-piece-item__name
          = art_piece.name.to_s
        .art-piece-item__author-price-wrapper
          .art-piece-item__author
            = art_piece.author
          .art-piece-item__price
            = art_piece.price

app/views/art_pieces/show.slim
.art-piece-wrapper
  .art-piece-image
    img[src=art_piece.image]
  .art-piece-description
    h1.art-piece-description__name
      = art_piece.name
    h4.art-piece-description__author
      = art_piece.author.name
    .art-piece-description__price
      = price_in_pounds art_piece.price
    .art-piece-description__description
      = raw art_piece.description_with_line_breaks
    .art-piece-buttons
      .art-piece-button-wrapper
        = link_to t('art_pieces.add_to_cart'), '#', class: 'art-piece-buttons__add-to-cart'
      .art-piece-button-wrapper
        = link_to t('art_pieces.make_an_offer'), '', class: 'art-piece-buttons__make-offer'
= render partial: 'art_pieces/show/make_offer_modal', locals: { }

app/views/art_pieces/show/_make_offer_modal.slim
.art-piece-make-an-offer-modal
  = render partial: 'shared/overlay_modal_close_button', locals: { html: { class: 'art-piece-make-an-offer-modal__close-button', modal_class: 'art-piece-make-an-offer-modal' } }
  .art-piece-make-an-offer-modal__inner
    h1.art-piece-make-an-offer-modal__header Make an offer
    form[action='get' url='#' class='art-piece-make-an-offer-modal__form']
      .art-piece-make-an-offer-modal__email.fieldset
        = label_tag 'email', 'Your email'
        = email_field_tag 'email', nil, placeholder: 'john.smith@gmail.com'
      .art-piece-make-an-offer-modal__message.fieldset
        = label_tag 'message', 'Message body'
        = text_area_tag 'message', "Dear Sir/Madam, I'd like to make an offer of #{price_in_pounds(art_piece.price)} for #{art_piece.name} by #{art_piece.artist.name}", rows: 6
      .art-piece-make-an-offer-modal__send.fieldset
        = button_tag "Send offer"

app/views/artists/index.slim
.artists-wrapper
  - artists.each do |artist|
    .artist-item
      = link_to artist_path(artist), class: 'artist-item__link'
        .artist-item__image-wrapper
          .artist-item__image
            img[class=artist.art_pieces.highlighted.first.decorate.wide_or_tall?
              src=artist.art_pieces.highlighted.first.image.url]
        .artist-item__name
          = artist.name

app/views/artists/show.slim
.artist-description-wrapper
  .artist-description
    h1.artist-description__name= artist.name
    p.artist-description__description= artist.description
    .artist-description__link
      = link_to t('artist.art_pieces'), gallery_filtered_by_artist_path(artist), class: 'artist-art-pieces'
    .artist-description__link
      a.artist-related-articles href='#' = t('artist.related_articles')

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : t('so_contemporary_art')
    = stylesheet_link_tag 'application'
    / = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'
    = javascript_include_tag :modernizr
    = csrf_meta_tags
  body
    = render 'shared/navigation'
    .wrapper
      = yield
    = render 'shared/footer'
    = javascript_include_tag 'application'

app/views/layouts/artist.slim
doctype html
html lang="en"
  head
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : t('so_contemporary_art')
    = stylesheet_link_tag 'application'
    / = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'
    = javascript_include_tag :modernizr
    = csrf_meta_tags
  body
    .artist-wrapper.wrapper[style="background-image:url('#{artist.art_pieces.highlighted.first.image.url}');"]
      = render 'shared/navigation'
      = yield
    = render 'shared/footer'
    = javascript_include_tag 'application'

app/views/shared/_footer.slim
footer
  .footer-social.footer-section
    a.footer-link.footer-social-link href='https://www.facebook.com/socontemporaryart'
      i.fa.fa-facebook
    a.footer-link.footer-social-link href='https://twitter.com/so_contemporary'
      i.fa.fa-twitter
    a.footer-link.footer-social-link href='http://instagram.com/so_contemporary'
      i.fa.fa-instagram
  .footer-about.footer-section
    a.footer-link.footer-about-link href='#'= t('footer.about_us')
    a.footer-link.footer-about-link href='#'= t('footer.contact')
    a.footer-link.footer-about-link href='#'= t('footer.returns_and_terms')
    a.footer-link.footer-about-link href='#'= t('footer.so_contemporary_art')

app/views/shared/_navigation.slim
nav
  ul.nav-items.primary
    li.nav-logo.nav-item
      a href='/'
        img.so-logo src="#{image_path('so-logo.jpg')}"
    li.nav-item
      a.nav-link href=gallery_path = t('navigation.gallery')
    li.nav-item
      a.nav-link href=artists_path = t('navigation.artists')
    li.nav-item
      a.nav-link href='#'= t('navigation.shop')
    li.nav-item
      a.nav-link href='#'= t('navigation.channel')
    li.nav-item
      a.nav-link href='#'= t('navigation.articles')
  ul.nav-items.secondary
    li.nav-item.nav-menu
      button.nav-menu-button[type='button' role='button' aria-label='Toggle Navigation']
        span.nav-menu-button__lines
    li.nav-logo.nav-item
      a href='/'
        img.so-logo src="#{image_path('so-logo.jpg')}"
    li.nav-cart.nav-item
      button.nav-cart-button
        i.fa.fa-shopping-cart
  .nav-overlay-items
    ul
      li.nav-overlay-item.nav-overlay-logo
        a href='/'
          img.so-logo src="#{image_path('so-logo.jpg')}"
      li.nav-overlay-item
        a.nav-link href=gallery_path = t('navigation.gallery')
      li.nav-overlay-item
        a.nav-link href=artists_path = t('navigation.artists')
      li.nav-overlay-item
        a.nav-link href='#'= t('navigation.shop')
      li.nav-overlay-item
        a.nav-link href='#'= t('navigation.channel')
      li.nav-overlay-item
        a.nav-link href='#'= t('navigation.articles')

app/views/shared/_overlay_modal_close_button.slim
button.close-overlay-modal-button[type='button' role='button' aria-label='Close' class=html[:class] data-modal-class=html[:modal_class]]
  span.close-overlay-modal-button__lines

app/views/static_pages/about.slim
.container
  h3 We happy?
  p My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?

  h3 Uuummmm, this is a tasty burger!
  p Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'?